services:
  server:
    build:
      context: ./wunderscout_be
      target: development
      dockerfile: Dockerfile
    env_file:
      - ./wunderscout_be/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./wunderscout_be:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - rabbitmq
  worker:
    build:
      context: ./wunderscout_worker
      target: development
      dockerfile: Dockerfile
    env_file:
      - ./wunderscout_worker/.env
    develop:
      watch:
        - action: sync
          path: ./wunderscout_worker
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./wunderscout_worker/pyproject.toml
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    hostname: some-rabbit
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:8.2-bookworm
    container_name: redis-dev
    ports:
      - 6379:6379
