/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/games/{gameId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get game data */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Game Id */
          gameId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                players: {
                  id: number;
                  name: string;
                  team_name: string;
                  artifacts: string[];
                }[];
                teams: {
                  id: number;
                  name: string;
                  artifacts: string[];
                }[];
              };
            };
          };
        };
        /** @description Invalid request parameters */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                type: string;
                code: string;
                message: string;
                status: number;
              };
            };
          };
        };
        /** @description Game not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                type: string;
                code: string;
                message: string;
                status: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiError: {
      error: {
        type: string;
        code: string;
        message: string;
        status: number;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

export type GameData =
  paths["/games/{gameId}"]["get"]["responses"]["200"]["content"]["application/json"];
export type ApiError = components["schemas"]["ApiError"];
